algoritmo "exerc71"
// Fun??o : Fa?a um programa que preencha automaticamente um vetor num?rico com 8
//posi??es, conforme abaixo:
//999 999 999 999 999 999 999 999
// 0   1   2   3   4   5   6   7
// Autor :  Nathan
// Data : 10/10/2022
// Lista de Exerc?cios do Curso Em Video - Prof: Gustavo Guanabara
var
   Vet: vetor[0..7] de inteiro
   C: inteiro
inicio
   para C <- 0 ate 7 faca
      Vet[C] <- 999
      escreva (Vet[C])
   Fimpara
fimalgoritmo