algoritmo "exerc06"
// Fun??o :  Leitura de um n?meo inteiro mostrando antecessor e sucessor.
// Autor :  Nathan
// Data : 10/10/2022
// Lista de Exerc?cios do Curso Em Video - Prof: Gustavo Guanabara
var
   N, Na, Ns: inteiro
inicio
   escreva ("Digite um n?mero: ")
   leia (N)
   Na <- N - 1
   Ns <- N + 1
   escreval ("O antecessor de ", N, " ? ", Na)
   escreva ("O sucessor de ", N, " ? ", Ns)

fimalgoritmo