algoritmo "exerc39"
// Fun??o : Fa?a um algoritmo que mostre na tela a seguinte contagem:
//10 9 8 7 6 5 4 3 Acabou!
// Autor :  Nathan
// Data : 10/10/2022
// Lista de Exerc?cios do Curso Em Video - Prof: Gustavo Guanabara
var
   Cont: Inteiro
inicio
   Cont <- 10
   enquanto (Cont >= 3) faca
      escreva (Cont)
      Cont <- Cont - 1
   Fimenquanto
   escreva (" Acabou!")
fimalgoritmo