algoritmo "exerc40"
// Fun??o : Crie um aplicativo que mostre na tela a seguinte contagem:
//0 3 6 9 12 15 18 Acabou!
// Autor :  Nathan
// Data : 10/10/2022
// Lista de Exerc?cios do Curso Em Video - Prof: Gustavo Guanabara
var
   Cont: Inteiro
inicio
   Cont <- 0
   enquanto (Cont <= 18) faca
      escreva (Cont)
      Cont <- Cont + 3
   Fimenquanto
   escreva (" Acabou!")
fimalgoritmo