algoritmo "exerc04"
// Fun??o : Algoritimo para ler dois n?meros inteiros e mostrar o somat?rio entre eles.
// Autor :  Nathan
// Data : 10/10/2022
// Lista de Exerc?cios do Curso Em Video - Prof: Gustavo Guanabara
var
   v1, v2, Soma: inteiro

inicio
   escreva ("Digite um valor: ")
   leia (v1)
   escreva ("digite outro valor: ")
   leia (v2)
   Soma <- v1 + v2
   escreva ("A soma entre ", v1, " e", v2, " ? igual a ", Soma, ".")
fimalgoritmo