algoritmo "exerc05"
// Fun??o :  Fazer programa que leia duas notas de um aluno e mostre a m?dia.
// Autor :  Nathan
// Data : 10/10/2022
// Lista de Exerc?cios do Curso Em Video - Prof: Gustavo Guanabara
var
   N1, N2, Med: real
inicio
   escreva ("Nota 1: ")
   leia (N1)
   escreva ("Nota 2: ")
   leia (N2)
   Med <- (N1 + N2)/2
   escreva ("A m?dia entre ", N1, " e", N2, " ? igual a ", Med)

fimalgoritmo